name-template: 'v$MAJOR.$MINOR.$PATCH'
tag-template: 'v$MAJOR.$MINOR.$PATCH'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Hotfixes'
    label: 'bug'
  - title: 'ETC'
    label: 'documentation'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What’s Changed

  $CHANGES
  $PREVIOUS_TAG
